#* Taran's GlazeWM V3 config :) *#

general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ['shell-exec %userprofile%/.glzr/zebar/start.bat']

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

gaps:
  # Gap between adjacent windows.
  inner_gap: '10px'

  # Gap between windows and the screen edge.
  # TODO: Change this to a suitable gap when the bar has been (re)created.
  outer_gap:
    top: '60px'
    right: '20px'
    bottom: '20px'
    left: '20px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: false
      color: '#a1a1a1'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling' # tiling>>>>>floating :)

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:

  # INFO: bind_to_monitor->0,1...n
    # 0 is your left most screen
    # 1 is your left most screen's right screen
    # n is your left most screen's right screen + 1
  
  - name: '1'
    display_name: 'Home'
    keep_alive: true
    bind_to_monitor: 0
  
  - name: '2'
    display_name: "Interwebs"
    bind_to_monitor: 1
    keep_alive: true
      
  - name: '3'
    display_name: "Dev"
    keep_alive: true
    bind_to_monitor: 0
  
  - name: '4'
    display_name: "Gaming"
    keep_alive: true
    bind_to_monitor: 1 
    # change it up and move all game launchers
    # to the 2nd monitor for a better list (preference ofc)
  
  - name: '5'
    display_name: "Media"
    keep_alive: true
    bind_to_monitor: 1
  
  - name: '6'
    display_name: "Social"
    keep_alive: true
    bind_to_monitor: 1
  
window_rules:
  - commands: ['ignore']

    # INFO: match_process_name->window_process
    # INFO: match_title->window_title
    # INFO: match_class_name->window_class
    
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys.PowerAccent' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

      # Taran's choice of apps to exclude via ignoring :D
      # INFO: Ignoring is floating now I think. It seems to work the same way...
      # UPDATE: Ignore literally ignores everything. It's not the same.
      
      - window_process: { equals: 'Flow.Launcher' }
      
      - window_process: { equals: '/Taskmgr|ScreenClippingHost/' }
      
      - window_process: { equals: "BakkesMod" } # while True: print("What a save!"*3, end="\n\n"); sleep(3)
    
  #* Move games to workspace 1 *#
  - commands: ['move --workspace 1']
    match:
      - window_process: { equals: "RobloxPlayerBeta" }
      - window_process: { equals: "destiny2" }

  - commands: ['move --workspace 2']
    match:
      - window_process: { equals: "chrome" }
      - window_process: { equals: "Arc" }

  - commands: ['move --workspace 3']
    match:
      - window_process: { equals: "Code" }
      - window_process: { equals: "sublime_text" }
  
  - commands: ['move --workspace 4']
    match:
      - window_process: { regex: "[Ss]team" }
      - window_process: { regex: "[Mm]inecraft [Ll]auncher" }
      - window_process: { equals: "EpicGamesLauncher" }
      - window_process: { equals: "Dolphin" }
  
  - commands: ['move --workspace 5']
    match:
      - window_process: { equals: "qbittorrent" }
      - window_process: { equals: "vlc" }
      - window_process: { equals: "Photos" }
      - window_process: { equals: "stremio" }
      - window_title: { equals: "Films & TV" }
    
  - commands: ['move --workspace 6']
    match:
      - window_process: { equals: "Discord" }
      - window_process: { equals: "LINE" }

  - commands: ['set-floating']
    match:
      - window_process: { equals: "wezterm-gui" }
      - window_process: { equals: "explorer" }
      - window_process: { equals: "SnippingTool" }
      - window_process: { equals: "TeraCopy" }
      - window_process: { equals: "Zen" }
      - window_title: { equals: 'FileBot' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+u']
  - commands: ['resize --width +2%']
    bindings: ['alt+p']
  - commands: ['resize --height +2%']
    bindings: ['alt+o']
  - commands: ['resize --height -2%']
    bindings: ['alt+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+x']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  # Terminal and Git Bash respectively.
  - commands: ['shell-exec %ProgramFiles%/WezTerm/wezterm-gui.exe']
    bindings: ['alt+enter']

  - commands: ['shell-exec %ProgramFiles%/Google/Chrome/Application/chrome.exe']
    bindings: ['alt+q']
  
  - commands: ['shell-exec %LOCALAPPDATA%/FlowLauncher/Flow.Launcher.exe']
    bindings: ['alt+space']
  
  #* Potentially goodbye to left/right_click_command, so I will have to work around it. *#
  - commands: ['shell-exec %userprofile%/.glzr/glazewm/helpers/SetWallpaper.exe']
    bindings: ['alt+shift+w']

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ['focus --next-workspace']
    bindings: ['alt+s']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  
  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
